module.exports= [
    { "key": "aerialway",
      "values" : [ { "@id": "drag_lift"} ,
        { "@id": "chair_lift"} ,
        { "@id": "cable_car"} ,
        { "@id": "aerialway_v_station"} ,
        { "@id": "pylon"} ,
        { "@id": "gondola"} ,
        { "@id": "goods"} ] } ,
    { "key": "aeroway",
      "values" : [ { "@id": "helipad"} ,
        { "@id": "aerodrome"} ,
        { "@id": "apron"} ,
        { "@id": "taxiway"} ,
        { "@id": "terminal"} ,
        { "@id": "runway"} ,
        { "@id": "gate"} ] } ,
    { "key": "amenity",
      "values" : [ { "@id": "hospital"} ,
        { "@id": "grave_yard"} ,
        { "@id": "kindergarten"} ,
        { "@id": "car_sharing"} ,
        { "@id": "car_wash"} ,
        { "@id": "casino"} ,
        { "@id": "cafe"} ,
        { "@id": "car_rental"} ,
        { "@id": "college"} ,
        { "@id": "charging_station"} ,
        { "@id": "cinema"} ,
        { "@id": "dentist"} ,
        { "@id": "community_centre"} ,
        { "@id": "courthouse"} ,
        { "@id": "drinking_water"} ,
        { "@id": "emergency_phone"} ,
        { "@id": "fast_food"} ,
        { "@id": "doctors"} ,
        { "@id": "airport"} ,
        { "@id": "atm"} ,
        { "@id": "arts_centre"} ,
        { "@id": "bench"} ,
        { "@id": "bicycle_parking"} ,
        { "@id": "bicycle_rental"} ,
        { "@id": "biergarten"} ,
        { "@id": "bank"} ,
        { "@id": "bar"} ,
        { "@id": "bureau_de_change"} ,
        { "@id": "bus_station"} ,
        { "@id": "telephone"} ,
        { "@id": "theatre"} ,
        { "@id": "swimming_pool"} ,
        { "@id": "taxi"} ,
        { "@id": "toilets"} ,
        { "@id": "town_hall"} ,
        { "@id": "waste_basket"} ,
        { "@id": "university"} ,
        { "@id": "veterinary"} ,
        { "@id": "post_box"} ,
        { "@id": "post_office"} ,
        { "@id": "pub"} ,
        { "@id": "place_of_worship"} ,
        { "@id": "police"} ,
        { "@id": "restaurant"} ,
        { "@id": "recycling"} ,
        { "@id": "school"} ,
        { "@id": "sauna"} ,
        { "@id": "shelter"} ,
        { "@id": "marketplace"} ,
        { "@id": "library"} ,
        { "@id": "nightclub"} ,
        { "@id": "parking"} ,
        { "@id": "pharmacy"} ,
        { "@id": "food_court"} ,
        { "@id": "ferry_terminal"} ,
        { "@id": "fire_station"} ,
        { "@id": "fountain"} ,
        { "@id": "fuel"} ] } ,
    { "key": "bicycle_parking",
      "values" : [ { "@id": "ground_slots"} ,
        { "@id": "anchors"} ,
        { "@id": "building"} ,
        { "@id": "stands"} ,
        { "@id": "wall_loops"} ,
        { "@id": "shed"} ,
        { "@id": "lockers"} ,
        { "@id": "informal"} ] } ,
    { "key": "building",
          "values" : [  ] } ,
    { "key": "boundary",
      "values" : [ { "@id": "administrative"} ,
          { "@id": "historic"} ,
          { "@id": "maritime"} ,
          { "@id": "national_park"} ,
          { "@id": "political"} ,
          { "@id": "postal_code"} ,
          { "@id": "religious_administration"} ,
          { "@id": "protected_area"} ,
          { "@id": "civil"} , ] } ,
    { "key": "castle_type",
      "values" : [ { "@id": "fortress"} ,
        { "@id": "defensive"} ,
        { "@id": "burg"} ,
        { "@id": "stately"} ,
        { "@id": "schloss"} ] } ,
    { "key": "place",
      "values" : [ { "@id": "country"} ,
        { "@id": "state"} ,
        { "@id": "region"} ,
        { "@id": "province"} ,
        { "@id": "district"} ,
        { "@id": "county"} ,
          { "@id": "municipality"},
        { "@id": "city"} ,
        { "@id": "borough"} ,
        { "@id": "suburb"} ,
        { "@id": "quarter"} ,
        { "@id": "neighbourhood"} ,
        { "@id": "city_block"},
        { "@id": "plot"},
        { "@id": "town"},
        { "@id": "village"},
        { "@id": "hamlet"},
        { "@id": "isolated_dwelling"},
        { "@id": "farm"},
        { "@id": "allotments"},
        { "@id": "continent"},
        { "@id": "archipelago"},
        { "@id": "island"},
        { "@id": "islet"},
        { "@id": "square"},
        { "@id": "locality"}] } ,
    { "key": "cuisine",
      "values" : [ { "@id": "turkish"} ,
        { "@id": "vegetarian"} ,
        { "@id": "cuisine_v_seafood"} ,
        { "@id": "american"} ,
        { "@id": "arabic"} ,
        { "@id": "asian"} ,
        { "@id": "burger"} ,
        { "@id": "chinese"} ,
        { "@id": "coffee_shop"} ,
        { "@id": "fish"} ,
        { "@id": "french"} ,
        { "@id": "german"} ,
        { "@id": "greek"} ,
        { "@id": "indian"} ,
        { "@id": "international"} ,
        { "@id": "italian"} ,
        { "@id": "japanese"} ,
        { "@id": "kebap"} ,
        { "@id": "mexican"} ,
        { "@id": "pizza"} ,
        { "@id": "regional"} ,
        { "@id": "spanish"} ,
        { "@id": "sushi"} ,
        { "@id": "thai"} ] } ,
    { "key": "denomination",
      "values" : [ { "@id": "baptist"} ,
        { "@id": "catholic"} ,
        { "@id": "lutheran"} ,
        { "@id": "methodist"} ,
        { "@id": "orthodox"} ,
        { "@id": "protestant"} ] } ,
    { "key": "emergency",
      "values" : [ { "@id": "emergency_v_no"} ,
        { "@id": "emergency_v_yes"} ,
        { "@id": "ambulance_station"} ,
        { "@id": "fire_hydrant"} ,
        { "@id": "phone"} ] } ,
    { "key": "geological",
      "values" : [ { "@id": "outcrop"},{ "@id": "moraine"},{ "@id": "palaeontological_site"} ] } ,
    { "key": "highway",
      "values" : [ { "@id": "steps"} ,
        { "@id": "tertiary"} ,
        { "@id": "bridleway"} ,
        { "@id": "bus_stop"} ,
        { "@id": "https://raw.github.com/doroam/planning-do-roam/master/Ontology/tags.owl#track"} ,
        { "@id": "cycleway"} ,
        { "@id": "footway"} ,
        { "@id": "path"} ,
        { "@id": "pedestrian"} ,
        { "@id": "living_street"} ,
        { "@id": "motorway"} ,
        { "@id": "motorway_link"} ,
        { "@id": "secondary"} ,
        { "@id": "secondary_link"} ,
        { "@id": "service"} ,
        { "@id": "services"} ,
        { "@id": "primary"} ,
        { "@id": "primary_link"} ,
        { "@id": "raceway"} ,
        { "@id": "residential"} ,
        { "@id": "trunk"} ,
        { "@id": "trunk_link"} ,
        { "@id": "unclassified"} ] } ,
    { "key": "historic",
      "values" : [ { "@id": "aircraft"} ,
        { "@id": "aqueduct"} ,
        { "@id": "archaeological_site"} ,
        { "@id": "battlefield"} ,
        { "@id": "boundary_stone"} ,
        { "@id": "building"} ,
        { "@id": "cannon"},
        { "@id": "castle"},
        { "@id": "city_gate"},
        { "@id": "citywalls"},
        { "@id": "farm"},
        { "@id": "fort"},
        { "@id": "gallows"},
        { "@id": "highwater_mark"},
        { "@id": "locomotive"},
        { "@id": "manor"},
        { "@id": "memorial"},
        { "@id": "milestone"},
        { "@id": "monastery"},
        { "@id": "monument"},
        { "@id": "optical_telegraph"},
        { "@id": "pillory"},
        { "@id": "railway_car"},
        { "@id": "ruins"},
        { "@id": "rune_ston"},
        { "@id": "ship"},
        { "@id": "tomb"},
        { "@id": "wayside_cross"},
        { "@id": "wayside_shrine"},
        { "@id": "wreck"} ] } ,
    { "key": "landuse",
      "values" : [ { "@id": "forest"},{ "@id": "residential"} ] } ,
    { "key": "leisure",
      "values" : [ { "@id": "stadium"} ,
        { "@id": "sports_centre"} ,
        { "@id": "swimming_pool"} ,
        { "@id": "arena"} ,
        { "@id": "dance"} ,
        { "@id": "common"} ,
        { "@id": "dog_park"} ,
        { "@id": "ice_rink"} ,
        { "@id": "fishing"} ,
        { "@id": "fitness_station"} ,
        { "@id": "golf_course"} ,
        { "@id": "garden"} ,
        { "@id": "nature_reserve"} ,
        { "@id": "picnic_table"} ,
        { "@id": "park"} ,
        { "@id": "marina"} ,
        { "@id": "miniature_golf"} ,
        { "@id": "slipway"} ,
        { "@id": "playground"} ,
        { "@id": "pitch"} ,
        { "@id": "recreation_ground"} ,
        { "@id": "track"} ,
        { "@id": "water_park"} ] } ,
    { "key": "man_made",
      "values" : [ { "@id": "storage_tank"} ,
        { "@id": "water_tower"} ,
        { "@id": "works"} ,
        { "@id": "environmental_hazard"} ,
        { "@id": "pier"} ,
        { "@id": "pipeline"} ,
        { "@id": "monitoring_station"} ,
        { "@id": "wastewater_plant"} ,
        { "@id": "tower"} ,
        { "@id": "survey_point"} ] } ,
    { "key": "military",
      "values" : [ { "@id": "bunker"} ,
        { "@id": "barracks"} ,
        { "@id": "bombcrater"} ,
        { "@id": "airfield"} ,
        { "@id": "danger_area"} ,
        { "@id": "naval_base"} ,
        { "@id": "nuclear_explosion_site"} ,
        { "@id": "range"} ] } ,
    { "key": "natural",
      "values" : [ { "@id": "wood"} ,
            {"@id": "tree_row"} ,
            {"@id": "tree"} ,
            {"@id": "scrub"} ,
            {"@id": "heath"} ,
            {"@id": "moor"} ,
            {"@id": "grassland"} ,
            {"@id": "fell"} ,
            {"@id": "bare_rock"} ,
            {"@id": "scree"} ,
            {"@id": "shingle"} ,
            {"@id": "sand"} ,
            {"@id": "mud"} ,
            {"@id": "water"} ,
            {"@id": "wetland"} ,
            {"@id": "glacier"} ,
            {"@id": "bay"} ,
            {"@id": "cape"} ,
            {"@id": "beach"} ,
            {"@id": "coastline"} ,
            {"@id": "spring"} ,
            {"@id": "hot_spring"} ,
            {"@id": "geyser"} ,
            {"@id": "peak"} ,
            {"@id": "volcano"} ,
            {"@id": "valley"} ,
            {"@id": "ridge"} ,
            {"@id": "arete"} ,
            {"@id": "cliff"} ,
            {"@id": "saddle"} ,
            {"@id": "rock"} ,
            {"@id": "stone"} ,
            {"@id": "sinkhole"} ,
            {"@id": "cave_entrance"}
         ] } ,
    { "key": "power",
      "values" : [ { "@id": "power_v_station"} ,
        { "@id": "power_v_tower"} ,
        { "@id": "line"} ,
        { "@id": "minor_line"} ,
        { "@id": "generator"} ,
        { "@id": "sub_station"} ,
        { "@id": "transformer"} ,
        { "@id": "pole"} ] } ,
    { "key": "power_source",
      "values" : [ { "@id": "power_source_v_no"} ,
        { "@id": "coal"} ,
        { "@id": "wind"} ,
        { "@id": "photovoltaic"} ,
        { "@id": "nuclear"} ,
        { "@id": "fossil"} ,
        { "@id": "gas"} ,
        { "@id": "hydro"} ,
        { "@id": "renewable"} ] } ,
    { "key": "railway",
      "values" : [ { "@id": "platform"} ,
        { "@id": "rail"} ,
        { "@id": "railway_v_tram"} ,
        { "@id": "crossing"} ,
        { "@id": "disused"} ,
        { "@id": "abandoned"} ,
        { "@id": "level_crossing"} ,
        { "@id": "halt"} ,
        { "@id": "tram_stop"} ,
        { "@id": "spur"} ,
        { "@id": "station"} ] } ,
    { "key": "religion",
      "values" : [ { "@id": "zoroastrian"} ,
        { "@id": "christian"} ,
        { "@id": "buddhist"} ,
        { "@id": "bahai"} ,
        { "@id": "pagan"} ,
        { "@id": "muslim"} ,
        { "@id": "pastafarian"} ,
        { "@id": "multifaith"} ,
        { "@id": "hindu"} ,
        { "@id": "jewish"} ,
        { "@id": "jain"} ,
        { "@id": "unitarian"} ,
        { "@id": "spiritualist"} ,
        { "@id": "taoist"} ,
        { "@id": "scientologist"} ,
        { "@id": "shinto"} ,
        { "@id": "sikh"} ] } ,
    { "key": "route",
      "values" : [ { "@id": "power"} ,
        { "@id": "route_v_bicycle"} ,
        { "@id": "route_v_subway"} ,
        { "@id": "detour"} ,
        { "@id": "bus"} ,
        { "@id": "piste"} ,
        { "@id": "mtb"} ,
        { "@id": "hiking"} ,
        { "@id": "ferry"} ,
        { "@id": "flightpath"} ,
        { "@id": "foot"} ,
        { "@id": "walking"} ,
        { "@id": "train"} ,
        { "@id": "tram"} ,
        { "@id": "truck"} ,
        { "@id": "trolleybus"} ,
        { "@id": "ski"} ,
        { "@id": "road"} ,
        { "@id": "railway"} ] } ,
    { "key": "shop",
      "values" : [ { "@id": "seafood"} ,
        { "@id": "shoes"} ,
        { "@id": "sports"} ,
        { "@id": "stationery"} ,
        { "@id": "supermarket"} ,
        { "@id": "toys"} ,
        { "@id": "travel_agency"} ,
        { "@id": "video"} ,
        { "@id": "florist"} ,
        { "@id": "furniture"} ,
        { "@id": "garden_centre"} ,
        { "@id": "hairdresser"} ,
        { "@id": "hardware"} ,
        { "@id": "kiosk"} ,
        { "@id": "jewelry"} ,
        { "@id": "laundry"} ,
        { "@id": "massage"} ,
        { "@id": "mall"} ,
        { "@id": "mobile_phone"} ,
        { "@id": "outdoor"} ,
        { "@id": "optician"} ,
        { "@id": "organic"} ,
        { "@id": "pet"} ,
        { "@id": "bakery"} ,
        { "@id": "beauty"} ,
        { "@id": "beverages"} ,
        { "@id": "bicycle"} ,
        { "@id": "books"} ,
        { "@id": "butcher"} ,
        { "@id": "car"} ,
        { "@id": "car_repair"} ,
        { "@id": "chemist"} ,
        { "@id": "clothes"} ,
        { "@id": "computer"} ,
        { "@id": "convenience"} ,
        { "@id": "deli"} ,
        { "@id": "department_store"} ,
        { "@id": "doityourself"} ,
        { "@id": "dry_cleaning"} ,
        { "@id": "electronics"} ] } ,
    { "key": "sport",
      "values" : [ { "@id": "skateboard"} ,
        { "@id": "skating"} ,
        { "@id": "skiing"} ,
        { "@id": "soccer"} ,
        { "@id": "tennis"} ,
        { "@id": "swimming"} ,
        { "@id": "table_tennis"} ,
        { "@id": "football"} ,
        { "@id": "golf"} ,
        { "@id": "hockey"} ,
        { "@id": "gymnastics"} ,
        { "@id": "multi"} ,
        { "@id": "athletics"} ,
        { "@id": "baseball"} ,
        { "@id": "basketball"} ,
        { "@id": "bowls"} ,
        { "@id": "climbing"} ,
        { "@id": "equestrian"} ] } ,
    { "key": "station",
      "values" : [ { "@id": "subway"} ] } ,
    { "key": "theatre:genre",
      "values" : [ { "@id": "puppet"} ,
        { "@id": "political"} ,
        { "@id": "shadow_play"} ,
        { "@id": "stand_up_comedy"} ,
        { "@id": "variet\u00E9"} ,
        { "@id": "figure"} ,
        { "@id": "marionette"} ,
        { "@id": "philharmonic"} ,
        { "@id": "musical"} ,
        { "@id": "opera"} ,
        { "@id": "ballet"} ,
        { "@id": "boulevard"} ,
        { "@id": "chamber_music"} ,
        { "@id": "comedy"} ,
        { "@id": "cabaret"} ,
        { "@id": "drama"} ] } ,
    { "key": "tourism",
      "values" : [ { "@id": "theme_park"} ,
        { "@id": "viewpoint"} ,
        { "@id": "information"} ,
        { "@id": "hotel"} ,
        { "@id": "guest_house"} ,
        { "@id": "hostel"} ,
        { "@id": "motel"} ,
        { "@id": "museum"} ,
        { "@id": "picnic_site"} ,
        { "@id": "attraction"} ,
        { "@id": "artwork"} ,
        { "@id": "alpine_hut"} ,
        { "@id": "chalet"} ,
        { "@id": "zoo"} ,
        { "@id": "camp_site"} ,
        { "@id": "caravan_site"} ] } ,
    { "key": "type",
      "values" : [ { "@id": "restriction"} ,
        { "@id": "site"} ,
        { "@id": "route"} ,
        { "@id": "multipolygon"} ,
        { "@id": "boundary"} ] } ,
    { "key": "waterway",
      "values" : [ { "@id": "river"} ,
        { "@id": "riverbank"} ,
        { "@id": "stream"} ,
        { "@id": "waterfall"} ,
        { "@id": "canal"} ,
        { "@id": "drain"} ,
        { "@id": "ditch"} ,
        { "@id": "dam"} ] }
]
